services: docker

language: python

python:
  - '3.8'

addons:
  apt:
    packages:
      - docker-ce

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv run pytest -v

deploy:
  # Deploy tag except "latest"
  - provider: script
    on:
      tags: true
      condition: $TRAVIS_TAG != latest
    script: ci/build-push.sh
    skip_cleanup: true
  # Deploy latest
  - provider: script
    on:
      branch: master
    script: ci/build-push.sh
    skip_cleanup: true
